import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const iPoppins = Poppins({ weight:['100','200','300','400','500','600','700','800'], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FlexForce Gymnasium",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={iPoppins.className}>
        <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  );
}
